apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: argocd

resources:
  - manifests/monitoring/namespace.yaml
  - manifests/monitoring/configmap.yaml